name: Markdown Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Check all markdown files in the repository
          args: --verbose --no-progress '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
